[2023-12-15T08:37:41.100-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DownloadMongoDBDAG.retrieve_and_save scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-12-15T08:37:41.106-0300] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DownloadMongoDBDAG.retrieve_and_save scheduled__2023-01-22T00:00:00+00:00 [queued]>
[2023-12-15T08:37:41.106-0300] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-15T08:37:41.126-0300] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): retrieve_and_save> on 2023-01-22 00:00:00+00:00
[2023-12-15T08:37:41.129-0300] {standard_task_runner.py:57} INFO - Started process 2925 to run task
[2023-12-15T08:37:41.132-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'DownloadMongoDBDAG', 'retrieve_and_save', 'scheduled__2023-01-22T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/download_mongo_dag.py', '--cfg-path', '/tmp/tmp4wyqjo_u']
[2023-12-15T08:37:41.133-0300] {standard_task_runner.py:85} INFO - Job 356: Subtask retrieve_and_save
[2023-12-15T08:37:41.176-0300] {task_command.py:416} INFO - Running <TaskInstance: DownloadMongoDBDAG.retrieve_and_save scheduled__2023-01-22T00:00:00+00:00 [running]> on host JulioPC.
[2023-12-15T08:37:41.223-0300] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='DownloadMongoDBDAG' AIRFLOW_CTX_TASK_ID='retrieve_and_save' AIRFLOW_CTX_EXECUTION_DATE='2023-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-01-22T00:00:00+00:00'
[2023-12-15T08:37:42.237-0300] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/julioubuntu/Projects/EGD/airflow-trabalho-final/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/julioubuntu/Projects/EGD/airflow-trabalho-final/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/julioubuntu/Projects/EGD/airflow-trabalho-final/airflow_pipeline/dags/download_mongo_dag.py", line 32, in retrieve_and_save_data_locally
    with open(local_file_path, 'w') as local_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/julioubuntu/Projects/EGD/airflow-trabalho-final/datalake/Gold/MongoDB/part-00000-a6e8f18b-a573-4b60-9d3a-6cc0cd21b30f-c000.json'
[2023-12-15T08:37:42.242-0300] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=DownloadMongoDBDAG, task_id=retrieve_and_save, execution_date=20230122T000000, start_date=20231215T113741, end_date=20231215T113742
[2023-12-15T08:37:42.256-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 356 for task retrieve_and_save ([Errno 2] No such file or directory: '/home/julioubuntu/Projects/EGD/airflow-trabalho-final/datalake/Gold/MongoDB/part-00000-a6e8f18b-a573-4b60-9d3a-6cc0cd21b30f-c000.json'; 2925)
[2023-12-15T08:37:42.273-0300] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-15T08:37:42.283-0300] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
